<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIT8H0DN\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIT8H0DN/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerIT8H0DN.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerIT8H0DN\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerIT8H0DN\App_KernelDevContainer([
    'container.build_hash' => 'IT8H0DN',
    'container.build_id' => 'fc7feb79',
    'container.build_time' => 1636314812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIT8H0DN');
