<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8zVq4u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8zVq4u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD8zVq4u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD8zVq4u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD8zVq4u\App_KernelDevDebugContainer([
    'container.build_hash' => 'D8zVq4u',
    'container.build_id' => '502f2cde',
    'container.build_time' => 1636316346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8zVq4u');
