<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFfrBJMz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfrBJMz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFfrBJMz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFfrBJMz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFfrBJMz\App_KernelDevDebugContainer([
    'container.build_hash' => 'FfrBJMz',
    'container.build_id' => 'c997efe9',
    'container.build_time' => 1636440243,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfrBJMz');
